site_name: Mathematics for Data Science 1
site_author: Sadaan Baksh and Manish Kumar Sahani

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo

nav:
  - Home: index.md
  - Week 1: notes/week-1.md
  - PYQS: pyqs/main.md
